package org.xaspect;

import org.xaspect.services.ServiceRunner;
import org.xaspect.services.XClockCoroutineManager;


/**
 * This class requires quasar runtime! so introducing quasar dependency and agent. Please refer to the doc.
 * To pass the compilation, add the snippet following to your pom:
 *         <dependency>
 *             <groupId>co.paralleluniverse</groupId>
 *             <artifactId>quasar-core</artifactId>
 *             <version>0.8.0</version>
 *         </dependency>
 *
 * @param <DUT>： Set this type to the DUT class generated by the picker tool, e.g. UT_ALU
 *             请将这里的泛型类型设置为picker生成的最终DUT类，比如，UT_ALU
 */
public interface DUTCoroutineManager<DUT> extends DUTManager<DUT> {
    ServiceRunner getServiceRunner();

    @Override
    XClockCoroutineManager getXClockManager();
}
